(function(){
	'use strict';

angular.module("Hangman")
	.service("AlphabetsArray",AlphabetsArray);

function AlphabetsArray(){
		this.alphabetArray=[
		{
			"charVal":"a",
			"disabledChar":false
		},{
			"charVal":"b",
			"disabledChar":false
		},{
			"charVal":"c",
			"disabledChar":false
		},{
			"charVal":"d",
			"disabledChar":false
		},{
			"charVal":"e",
			"disabledChar":false
		},{
			"charVal":"f",
			"disabledChar":false
		},{
			"charVal":"g",
			"disabledChar":false
		},{
			"charVal":"h",
			"disabledChar":false
		},{
			"charVal":"i",
			"disabledChar":false
		},{
			"charVal":"j",
			"disabledChar":false
		},{
			"charVal":"k",
			"disabledChar":false
		},{
			"charVal":"l",
			"disabledChar":false
		},{
			"charVal":"m",
			"disabledChar":false
		},{
			"charVal":"n",
			"disabledChar":false
		},{
			"charVal":"o",
			"disabledChar":false
		},{
			"charVal":"p",
			"disabledChar":false
		},{
			"charVal":"q",
			"disabledChar":false
		},{
			"charVal":"r",
			"disabledChar":false
		},{
			"charVal":"s",
			"disabledChar":false
		},{
			"charVal":"t",
			"disabledChar":false
		},{
			"charVal":"u",
			"disabledChar":false
		},{
			"charVal":"v",
			"disabledChar":false
		},{
			"charVal":"w",
			"disabledChar":false
		},{
			"charVal":"x",
			"disabledChar":false
		},{
			"charVal":"y",
			"disabledChar":false
		},{
			"charVal":"z",
			"disabledChar":false
		},{
			"charVal":"1",
			"disabledChar":false
		},{
			"charVal":"2",
			"disabledChar":false
		},{
			"charVal":"3",
			"disabledChar":false
		},{
			"charVal":"4",
			"disabledChar":false
		},{
			"charVal":"5",
			"disabledChar":false
		},{
			"charVal":"6",
			"disabledChar":false
		},{
			"charVal":"7",
			"disabledChar":false
		},{
			"charVal":"8",
			"disabledChar":false
		},{
			"charVal":"9",
			"disabledChar":false
		},{
			"charVal":"0",
			"disabledChar":false
		}	
	];
};
})();